### ISSUE TITLE
サンプルを実行できた人はここにコメントお願いします。

### ISSUE THREAD

**Issue by dashimaki360** [OneNightROBOCON/turtle_war#2]
サンプルを実行できた人はこのissueにコメントお願いします。

**Comment by dashimaki360** [comment]
できました! (できて当然)

**Comment by t-kishi** [comment]
サンプル実行できました！
すみません，スコア表示に取り組もうと思いましたが，もう完成していました．

**Comment by gogo5nta** [comment]
サンプル実行できました！
Git Topページを参考に、一括インストール用のshellを作りました。
--- setting_for_robocon170715.sh ---
#!/bin/sh
echo "turtlebot install"

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install ros-indigo-turtlebot ros-indigo-turtlebot-apps ros-indigo-turtlebot-interactions ros-indigo-turtlebot-simulator ros-indigo-kobuki-ftdi ros-indigo-rocon-remocon ros-indigo-rocon-qt-library ros-indigo-ar-track-alvar-msgs -y

echo "python OppenCV setting"
sudo apt-get install python-numpy -y
sudo apt-get install python-opencv -y

echo "Get turtle_war"
cd ~/catkin_ws/src
git clone https://github.com/OneNightROBOCON/turtle_war

echo "catkin make"
cd ~/catkin_ws
catkin_make

echo "run turtle_war"
roscd turtle_war
chmod 777 start.sh
bash start.sh
----------------------------------------------------------------------------------------

**Comment by nodaki** [comment]
サンプル作成ありがとうございます。無事サンプル動かすことができました！

**Comment by dashimaki360** [comment]
報告ありがとうございます。無事できているようで安心しました。
@gogo5nta 一括スクリプト作成ありがとうございます!!　リポジトリに追加します。

**Comment by yukiimai** [comment]
ROS:kinetic Ubuntu16.04 64bitでサンプル実行できました。

**Comment by dashimaki360** [comment]
@yukiimai 動きましたか!
kinetic は　GAZEBOバージョンあがりまくって、安定してるらしいんで引っ越ししたいなー

**Comment by yukiimai** [comment]
同一マシンで比較はしていないですが、動作が軽い気がします。GAZEBO Version 7.0

**Comment by life-bluewater** [comment]
動作しました！

**Comment by kawata-yasuo** [comment]
サンプル実行できました！
が、ノートPCのスペックが低いため、描画がカクカク＆マウスが効かない感じでした。。。

**Comment by dashimaki360** [comment]
@kawata-yasuo 
環境がvirtualboxでしたら設定を見直すとましになるかもしれません。
くわしくはwikiを参照ください↓
https://github.com/OneNightROBOCON/turtle_war/wiki/virtualbox%E9%96%A2%E9%80%A3

**Comment by takeoverjp** [comment]
動作しました！
